server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: lb://serviceA
          predicates:
            - Path=/service-a/**
          filters:
            - StripPrefix=1
        - id: serviceB
          uri: lb://serviceB
          predicates:
            - Path=/service-b/**
          filters:
            - StripPrefix=1
        - id: serviceC
          uri: lb://serviceC
          predicates:
            - Path=/service-c/**
          filters:
            - StripPrefix=1

eureka:
  #  instance:
  #    #续约发送间隔默认30秒，心跳间隔
  #    lease-renewal-interval-in-seconds: 5
  #    # 续约到期时间（默认90秒）
  #    lease-expiration-duration-in-seconds: 15
  client:
    #    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    #    registry-fetch-interval-seconds: 5
    #    healthcheck:
    #      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
